[package]
name = "pokemonNotifications"
version = "0.1.0"
edition = "2021"


[dependencies]
reqwest = { version = "0.11", features = ["cookies"] }
tokio = { version = "1", features = ["full"] }
dotenvy = "0.15"
scraper = "0.12"
lettre = "0.10"
