[package]
name = "pokemonNotifications"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.11", features = ["json"] }
lettre = "0.10"
tokio = { version = "1", features = ["full"] }

